### ISSUE TITLE
auto initialization of ConstBitStream doesn't work with uint64

### ISSUE THREAD

**Issue by mexanick** [scott-griffiths/bitstring#205] opened 2020-05-11 21:36 UTC
```python
cbs = ConstBitStream(filename=filename)
word = cbs.read('uintle:64')
#This works
bitword = ConstBitStream(uint=word, length=64)
#This doesn't
bitword = ConstBitStream(word)
```
Error:
```
MemoryError                               Traceback (most recent call last)
<ipython-input-16-cfa127ea649a> in <module>
     10 word = cbs.read('uintle:64')
     11 #bitword = ConstBitStream(uint=word, length=64)
---> 12 bitword = ConstBitStream(word)
     13 vals = bitword.readlist('uint:4, uint:4, uint:24, uint:12, uint:12')
     14 labels = ['BOE N', 'EvtType', 'L1A ID', 'BX ID', 'SRC ID']

~/work/venv-python3/lib/python3.7/site-packages/bitstring.py in __new__(cls, auto, length, offset, **kwargs)
   3855     def __new__(cls, auto=None, length=None, offset=None, **kwargs):
   3856         x = super(ConstBitStream, cls).__new__(cls)
-> 3857         x._initialise(auto, length, offset, **kwargs)
   3858         return x
   3859 

~/work/venv-python3/lib/python3.7/site-packages/bitstring.py in _initialise(self, auto, length, offset, **kwargs)
    851             raise CreationError("offset must be >= 0.")
    852         if auto is not None:
--> 853             self._initialise_from_auto(auto, length, offset)
    854             return
    855         if not kwargs:

~/work/venv-python3/lib/python3.7/site-packages/bitstring.py in _initialise_from_auto(self, auto, length, offset)
    882         if offset is None:
    883             offset = 0
--> 884         self._setauto(auto, length, offset)
    885         return
    886 

~/work/venv-python3/lib/python3.7/site-packages/bitstring.py in _setauto(self, s, length, offset)
   1361                 msg = "Can't create bitstring of negative length {0}."
   1362                 raise CreationError(msg, s)
-> 1363             data = bytearray((s + 7) // 8)
   1364             self._datastore = ByteStore(data, s, 0)
   1365             return

MemoryError: 
```

**Comment by scott-griffiths** [comment] 2020-05-11 22:32
Hi,

Reading the `uintle:64` will read the next 8 bytes, interpret them as a little endian integer and return that integer. So it's likely to be an integer that needs all 64 bits.

When you try to create the `ConstBitStream` object with `word` it is trying to create an new bitstring with `word` zero bits. It doesn't have any method of guessing your intention.

So that's likely to be of the order of 2^63 zero bits, which is roughly 1,000,000 GB of memory. So if your computer has less than that (and I'm pretty sure it does!) then you get a `MemoryError`.

It works fine for me if word is a reasonable number so closing as not a bug.

Thanks anyway.

**Closed by scott-griffiths** 2020-05-11 22:32 UTC
