### ISSUE TITLE
Changing bit-wise endian-ness

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scott-griffiths/bitstring#142] opened 2015-04-11 20:51 UTC
```
I am trying to use the bitstring module to parse into corrupt gzip files.  
Unfortunately, the gzip and zlib specs treat byte data as if the least 
significant bit came first in the file.

(see
http://www.gzip.org/zlib/rfc-gzip.html
http://www.gzip.org/zlib/rfc-deflate.html
)

At https://pythonhosted.org/bitstring/creation.html#from-an-integer, there is 
an allusion to bytes being bit-wise big-endian, but I can't find any way to 
change that interpretation in the docs.

For example, the first byte of a deflated block from a known good gzipped file 
happens to be 0xec.  Using bitstring as is, the first three bits come back as 
0b111, which indicates 'final block, error in compression.'  When read as 
bit-wise little-endian, I'd get 0b001, which is 'not-final block, fixed Huffman 
encoding.'

is there any way to change bit-wise endian-ness?

```

Original issue reported on code.google.com by `j...@clkda.com` on 11 Mar 2014 at 7:23

**Comment by florisla** [comment] 2018-07-27 15:04
I think the same issue is discussed now in #156.

**Comment by scott-griffiths** [comment] 2020-05-05 20:23
Closing as a duplicate of the discussion in Issue #156

**Closed by scott-griffiths** 2020-05-05 20:23 UTC
Labels: auto-migrated
