### ISSUE TITLE
Matching C order for bit packed structs.

### ISSUE THREAD

**Issue by taylorh140** [scott-griffiths/bitstring#341] opened 2024-07-29 14:37 UTC
```python
import bitstring
from bitstring import Bits,pack
from collections import namedtuple

bitstring.options.lsb0 = True

types = "=B,bool,pad7"

data = pack(types,0xAA,True) #pack the bytes 

for i in data.bytes: # print out each byte
	print(hex(i))
```
python output:
```
0x1 0xaa
```

```c
#include <stdio.h>

typedef struct {
    unsigned char Q:8;
    _Bool A:1;
    int    :7;
} stuff_t;

int main() {
    // Write C code here
    stuff_t B = {.Q=0xAA,.A=1}; //pack the bytes
    
    for(int i=0;i<2;i++){ // print out each byte
        unsigned char * D = (unsigned char*)(void*)&B;
        printf("0x%02x",*(D+i));
    }
    return 0;
}
```
c results:
```
0xaa 0x01
```

The problem here is that they are reversed from what i would expected.

**Comment by taylorh140** [comment] 2024-07-29 16:26
And it seems like here it would be as easy as reversing the bits. But it isn't. it messes with the endianness of stored data.

**Comment by taylorh140** [comment] 2024-07-29 16:44
A uneasy hack that seems to makes these match is :
```
bitstring.options.lsb0 = True
reverse endianess on all Dtypes.

unpacking:
 - reverse incoming data. data[::-1]
 - unpack
 
 packing:
 - pack input data
 - reverse byte order before sending. data[::-1]

```


I'm hoping there is a better way.

**Comment by scott-griffiths** [comment] 2024-07-30 12:15
Hi.

I think that `pack` is working as intended here. The LSB0 mode means that reads, slices etc. are happening from right to left, so for example the reverse operation

```
>>> data.unpack(types)
[170, True]
```

is what you'd expect. When the data is unpacked here it does the right-most byte first, then the next bit. This is correct and I think it's reasonable that pack should behave in the same way.

I think there is some confusion because for this particular case reversing the byte order exactly reverses the effect of LSB0 (as both things are contained in one byte). Reversing byte order won't work in general.

Your C code is implicitly MSB0, so possibly you don't need LSB0 mode at all?

**Comment by scott-griffiths** [comment] 2024-08-01 10:53
OK, I think you're right and hopefully I get it now. The C compiler is packing the bitfields in a LSB0 manner (this is I think compiler dependent), but only the bitfields. The larger byte structures are still being packed left-to-right.

So in the original struct 

```
typedef struct {
    unsigned char Q:8;
    _Bool A:1;
    int    :7;
} stuff_t;
```

the `char` comes first, then the bitfields are packed LSB0 so it's the `int` followed by the `_Bool`. So reading left-to-right it's the first member of the struct, then the third, then the second. That's how you get the final `0xaa 0x01` output.

In bitstring with LSB0 the equivalent does the 3rd then 2nd then 1st field (reading left-to-right). For MSB0 it does it the opposite way round. So neither will match the C code.

I don't think there's anything that bitstring can do here - the packing rules of a particular C compiler are a bit out of scope. I think I would keep it in MSB0, and then try to reverse the C-packed bitfields for whichever rules the compiler has. In general a mix of bit and byte endianness!

**Comment by taylorh140** [comment] 2024-08-01 17:18
Its somewhat interesting that this hasn't shown up more often. given that pythons' own ctypes assumes the same order for little endian chips. 

i actually put together something to pack and unpack these using ctypes:


[ExtStruct.txt](https://github.com/user-attachments/files/16459844/ExtStruct.txt)


its actually a python file. but it gives an example of how the packing is assumed in c python. it matches gcc. armcc. and ctypes. for x86

**Closed** 2024-08-15 12:29 UTC

**Comment by fdwr** [comment] 2025-02-05 06:36
> The C compiler is packing the bitfields in a LSB0 manner
> ...
> Its somewhat interesting that this hasn't shown up more often

> [!NOTE] 
> Indeed! It's tangentially related to [my issue](https://github.com/scott-griffiths/bitstring/issues/354). C/C++ compilers targeting little-endian machines arrange bitfields in increasing bit order (from the LSB to the MSB of the base storage unit) and bytes also in increasing order, whereas C compilers targeting big-endian machines *generally* do the reverse (bitfields arranged from MSB to LSB) but bytes still in increasing order, with the known exception of the [C51 8051 microcontroller compiler](https://developer.arm.com/documentation/ka004521) which lays bitfields out in LSB->MSB order within each byte (like LE) but then swaps the bytes in the word ([reference](https://stackoverflow.com/questions/22189555/endianness-within-uint12-struct/74298520)).

| Architecture          | Bitfield direction in storage unit | Byte direction of bitfields in storage unit | Byte direction of *overall* fields in struct |
|---------------------|--------------------|----------------|----------------------|
| Little endian          | increasing bit index | increasing byte | increasing byte |
| Big endian (most) | decreasing bit index | increasing byte | increasing byte |
| Big endian (C51 8051) | increasing bit index | decreasing byte | increasing byte |
