### ISSUE TITLE
Bits(bitstream) still mutable Bitstream object

### ISSUE THREAD

**Issue by koppa** [scott-griffiths/bitstring#157] opened 2016-03-14 05:51 UTC
Unexpected behaviour (probably a bug), when casting to a Bits object

Currently:

    bs = BitStream()
    bt = Bits(bs)
    # type(bt) == BitStream

The bt is the same instance as bs, therefore mutable

Possible fix

    src/lib/bitstring/bitstring.py
    @@ -787,7 +787,7 @@ class Bits(object):
                         if len(_cache) < CACHE_SIZE:
                             _cache[auto] = x
                         return x
    -            if isinstance(auto, Bits):
    +            if type(auto) == Bits:
                     return auto
             except TypeError:
                 pass

**Comment by scott-griffiths** [comment] 2016-03-14 16:30
Yes, you're right. It's already recorded as Bug #144, and your fix might well be right. I'm going to try to get a new point release out soonish, so it will be fixed then.

Cheers.

**Comment by scott-griffiths** [comment] 2016-03-14 16:31
Duplicate of #144.

**Closed by scott-griffiths** 2016-03-14 16:30 UTC
